In [2]:
import numpy as np

1. Creating tensor

In [9]:
T = np.array([ [[23,50],[7,12]], [[57,67],[99,43]], [[75,21],[57,12]], [[87,26],[18,84]] ])
print(T.shape)
print(T)

(4, 2, 2)
[[[23 50]
  [ 7 12]]

 [[57 67]
  [99 43]]

 [[75 21]
  [57 12]]

 [[87 26]
  [18 84]]]


2. Matrix multiplication

In [18]:
a = np.array ([[27,50,19],[7,12,109],[57,67,98]])
print(a.shape)
print(a)

b = np.array ([[17],[22],[19]])
print(b.shape)

multiplication = a * b
print(multiplication)


(3, 3)
[[ 27  50  19]
 [  7  12 109]
 [ 57  67  98]]
(3, 1)
[[ 459  850  323]
 [ 154  264 2398]
 [1083 1273 1862]]


3. Transpose, determinant and inverse

In [20]:
a_transpose = print(a.T)
det = np.linalg.det(a)
print(det)

[[ 27   7  57]
 [ 50  12  67]
 [ 19 109  98]]
106836.00000000017


In [23]:
print(np.linalg.inv(a))

[[-0.05734958 -0.03394923  0.04887866]
 [ 0.0517335   0.0146299  -0.026302  ]
 [-0.00201243  0.00974391 -0.00024336]]
